### PR TITLE
SRCH-2695 Indicate Deprecated Module Codes

### PR DESCRIPTION
**Pull request by amanifarooque**
## PR Checklist
- [x] Test Federalist Preview link for your branch for functionality - make sure all links and buttons work, javascript works as intended, and updates display as expected
- [x] Conduct a HemingwayApp review of the content for plain language. Request plain language review in #helpwanted if needed before merging this PR
- [N/A] Conduct a Lighthouse Audit via Chrome Developer Tools. Identify any issues that must be addressed before merging, and fix
- [x] Ensure no non-public information is published in the commit messages

### CODE REVIEW

**Comment by amanifarooque** [comment]
@dawnpm @MothOnMars  - I marked the following as deprecated:

- AWEB
- DECOR
- GWEB

Let me know if this list should be added or changed. Marking you both as reviewers for this PR - thanks!

**Comment by amanifarooque** [comment]
Federalist Preview Link: https://cg-a72b65a7-73f0-4859-a1d7-dc953cf6ade8.app.cloud.gov/preview/gsa/search-gov-website/afarooque/SRCH-2695-module-codes/admin-center/analytics/module-codes.html

**Comment by dawnpm** [comment]
@amanifarooque Should we just remove them entirely?

**Comment by amanifarooque** [comment]
Martha noted in the Jira item that some of these codes may have appeared in their click tracking analytics (most relevant for DECOR, which we just recently removed). I don't think it hurts to keep the legacy codes as long as we indicate that they're no longer used.

**Comment by dawnpm** [comment]
With the recent cleanout of older data, at least AWEB and GWEB are not going to be reported. Could remove those two and mark DECOR as deprecated?

**Comment by amanifarooque** [comment]
@dawnpm Will do, let me know if the changes are now approved!

**Review by dawnpm — APPROVED** [review]

**Review by MothOnMars — APPROVED** [review]
LGTM

**Pull request merged**
