### PR TITLE
Create Releases “2022-12-09-november-2022”

### PR DESCRIPTION
**Pull request by amanifarooque**
Automatically generated by Netlify CMS

### CODE REVIEW

**Comment by amanifarooque** [comment]
Preview URL: https://cg-a72b65a7-73f0-4859-a1d7-dc953cf6ade8.sites.pages.cloud.gov/preview/gsa/search-gov-website/cms/releases/2022-12-09-november-2022/about/updates/releases/november-2022.html

**Review by MyNameIsMissing — CHANGES_REQUESTED** [review]
I think you need a valid email address in the mailto link

**Comment by amanifarooque** [comment]
@MyNameIsMissing Good catch, updated.

**Review by MyNameIsMissing — APPROVED** [review]
LGTM

**Review by dawnpm — APPROVED** [review]
I rearranged the list order, and changed "SERP" to "Results Page". Merging.

**Pull request merged**
