### PR TITLE
Updates for RSS Feed Indexing

### PR DESCRIPTION
**Pull request by amanifarooque**
## Summary
Now that we support RSS feeds as sitemaps for indexing, we need to update sections across our website accordingly.

Updated Pages:

- https://cg-a72b65a7-73f0-4859-a1d7-dc953cf6ade8.sites.pages.cloud.gov/preview/gsa/search-gov-website/afarooque/rss-feed-updates/indexing/indexing-workflow.html
- https://cg-a72b65a7-73f0-4859-a1d7-dc953cf6ade8.sites.pages.cloud.gov/preview/gsa/search-gov-website/afarooque/rss-feed-updates/indexing/robotstxt.html
- https://cg-a72b65a7-73f0-4859-a1d7-dc953cf6ade8.sites.pages.cloud.gov/preview/gsa/search-gov-website/afarooque/rss-feed-updates/indexing/what-searchgov-indexes.html
- https://cg-a72b65a7-73f0-4859-a1d7-dc953cf6ade8.sites.pages.cloud.gov/preview/gsa/search-gov-website/afarooque/rss-feed-updates/indexing/how-search-engines-index-content-better-discoverability.html

## PR Checklist
- [x] Test Cloud.gov Pages preview link for your branch for functionality - make sure all links and buttons work, javascript works as intended, and updates display as expected
- [N/A] Conduct a HemingwayApp review of the content for plain language. Request plain language review in #helpwanted if needed before merging this PR
- [N/A] Conduct a Lighthouse Audit via Chrome Developer Tools. Identify any issues that must be addressed before merging, and fix
- [x] Ensure no non-public information is published in the commit messages

### CODE REVIEW

**Comment by amanifarooque** [comment]
@dawnpm Bumping this PR!

**Comment by dawnpm** [comment]
I think we may need to improve on "We understand it can be difficult for some legacy systems to generate a sitemaps, so if this is the case, [please reach out](mailto:search@gsa.gov). We also support valid [RSS 2.0](https://www.rssboard.org/rss-specification) and [Atom 2.0](https://validator.w3.org/feed/docs/atom.html) feeds for URL discovery." at some point, but we can wait for the questions to come in to direct our thinking in how to change it.

**Comment by amanifarooque** [comment]
@dawnpm Makes sense. For now, I've fixed the typo  - anything else needed before we approve/merge?

**Comment by dawnpm** [comment]
I'm making a few direct updates.

**Comment by amanifarooque** [comment]
LGTM!

**Pull request merged**
